include:
  - project: tilotech/template-gitlab-ci
    file: /golang-defaults.gitlab-ci.yml
  - project: tilotech/template-gitlab-ci
    file: /golang-license.gitlab-ci.yml
  - project: tilotech/template-gitlab-ci
    file: /golang-build.gitlab-ci.yml
