package cmd

const applicationName = "TiloRes"
const applicationNameLower = "tilores"
const toolName = "tilores-cli"
const generatedMsg = "Code generated by gitlab.com/tilotech/tilores-cli, DO NOT EDIT."
